"""
Geospatial index analysis utilities for TriNetra.

This module DOES NOT recalculate NDVI, NDWI or NDBI.

Those indices are already produced by:
    preprocessing.optical_processing.OpticalProcessor

This module converts those index arrays into geospatial evidence:

    Index Array
        ↓
    Statistics
        ↓
    Threshold / Region Mask
        ↓
    Pixel Count
        ↓
    Area Estimation
        ↓
    Structured Evidence

Designed for:
    - Single Image Analysis (SIA)
    - Bi-Temporal Processing (BTP)
    - Optical + SAR workflows
    - Agentic routing
    - Evidence-backed responses
"""

from pathlib import Path
from typing import Dict, Optional, Tuple

import numpy as np
import rasterio


class GeospatialIndexAnalyzer:
    """
    Analyze already-computed spectral indices geographically.

    Expected inputs:
        NDVI, NDWI or NDBI arrays generated by OpticalProcessor.

    The analyzer uses GeoTIFF spatial metadata to estimate:
        - statistics
        - coverage percentage
        - pixel counts
        - approximate area
        - significant regions
    """

    def __init__(
        self,
        raster_path: str,
    ):
        self.raster_path = Path(raster_path)

        if not self.raster_path.exists():
            raise FileNotFoundError(
                f"GeoTIFF file not found: {self.raster_path}"
            )

        if self.raster_path.suffix.lower() not in [".tif", ".tiff"]:
            raise ValueError(
                "Input file must be a GeoTIFF (.tif or .tiff)"
            )

        self.crs = None
        self.transform = None
        self.width = None
        self.height = None
        self.resolution = None

        self._load_spatial_metadata()

    # =========================================================
    # LOAD SPATIAL INFORMATION
    # =========================================================

    def _load_spatial_metadata(self):
        """
        Read only the geospatial metadata.

        The actual index calculation remains in preprocessing.
        """

        with rasterio.open(self.raster_path) as src:

            self.crs = src.crs
            self.transform = src.transform

            self.width = src.width
            self.height = src.height

            self.resolution = src.res

    # =========================================================
    # VALID INDEX CHECK
    # =========================================================

    @staticmethod
    def _prepare_index(index: np.ndarray) -> np.ndarray:
        """
        Validate and clean an index array.

        Expected index range:
            approximately -1 to +1
        """

        index = np.asarray(index, dtype=np.float32)

        if index.ndim != 2:
            raise ValueError(
                "Index must be a 2D NumPy array "
                "(height, width)."
            )

        index = index.copy()

        # Remove invalid values.
        index[~np.isfinite(index)] = np.nan

        # Spectral indices normally lie in [-1, 1].
        index[(index < -1) | (index > 1)] = np.nan

        return index

    # =========================================================
    # BASIC STATISTICS
    # =========================================================

    def statistics(
        self,
        index: np.ndarray
    ) -> Dict[str, float]:
        """
        Return basic statistics for an index.
        """

        index = self._prepare_index(index)

        valid = index[np.isfinite(index)]

        if valid.size == 0:
            return {
                "valid_pixels": 0,
                "mean": None,
                "median": None,
                "minimum": None,
                "maximum": None,
                "std": None,
            }

        return {
            "valid_pixels": int(valid.size),
            "mean": float(np.mean(valid)),
            "median": float(np.median(valid)),
            "minimum": float(np.min(valid)),
            "maximum": float(np.max(valid)),
            "std": float(np.std(valid)),
        }

    # =========================================================
    # VALID PIXELS
    # =========================================================

    def valid_pixel_count(
        self,
        index: np.ndarray
    ) -> int:
        """
        Count valid pixels in the index.
        """

        index = self._prepare_index(index)

        return int(
            np.count_nonzero(
                np.isfinite(index)
            )
        )

    # =========================================================
    # PIXEL AREA
    # =========================================================

    def pixel_area(self) -> Optional[float]:
        """
        Estimate area of one pixel in square metres.

        This is reliable when the dataset uses a projected CRS
        where the coordinate units represent metres.

        Returns:
            pixel area in m²
            or None when the CRS is geographic/non-metric.
        """

        if self.resolution is None:
            return None

        if self.crs is None:
            return None

        # Geographic CRS -> degrees, not suitable for directly
        # multiplying resolution values to obtain square metres.
        if self.crs.is_geographic:
            return None

        x_resolution = abs(float(self.resolution[0]))
        y_resolution = abs(float(self.resolution[1]))

        return x_resolution * y_resolution

    # =========================================================
    # AREA FROM MASK
    # =========================================================

    def area_from_mask(
        self,
        mask: np.ndarray
    ) -> Optional[float]:
        """
        Calculate area covered by a boolean mask.

        Returns:
            area in square metres, or None for geographic CRS.
        """

        mask = np.asarray(mask, dtype=bool)

        if mask.ndim != 2:
            raise ValueError(
                "Mask must be a 2D NumPy array."
            )

        pixel_area = self.pixel_area()

        if pixel_area is None:
            return None

        pixel_count = int(
            np.count_nonzero(mask)
        )

        return pixel_count * pixel_area

    # =========================================================
    # AREA IN SQUARE KILOMETRES
    # =========================================================

    def area_km2(
        self,
        mask: np.ndarray
    ) -> Optional[float]:
        """
        Calculate masked area in square kilometres.
        """

        area_m2 = self.area_from_mask(mask)

        if area_m2 is None:
            return None

        return area_m2 / 1_000_000.0

    # =========================================================
    # COVERAGE %
    # =========================================================

    def coverage_percentage(
        self,
        mask: np.ndarray,
        index: Optional[np.ndarray] = None
    ) -> float:
        """
        Calculate percentage of valid pixels represented
        by a boolean mask.

        Example:
            vegetation coverage = vegetated pixels /
                                  valid pixels × 100
        """

        mask = np.asarray(mask, dtype=bool)

        if mask.ndim != 2:
            raise ValueError(
                "Mask must be a 2D NumPy array."
            )

        if index is not None:

            index = self._prepare_index(index)

            valid_pixels = np.isfinite(index)

        else:

            valid_pixels = np.ones(
                mask.shape,
                dtype=bool
            )

        total_valid = int(
            np.count_nonzero(valid_pixels)
        )

        if total_valid == 0:
            return 0.0

        masked_valid = int(
            np.count_nonzero(
                mask & valid_pixels
            )
        )

        return (
            masked_valid /
            total_valid
        ) * 100.0

    # =========================================================
    # THRESHOLD MASK
    # =========================================================

    @staticmethod
    def threshold_mask(
        index: np.ndarray,
        threshold: float,
        condition: str = "greater"
    ) -> np.ndarray:
        """
        Create a boolean mask from an index.

        Supported conditions:

            greater
            greater_equal
            less
            less_equal
            between

        For 'between', threshold should be:
            (lower, upper)
        """

        index = np.asarray(
            index,
            dtype=np.float32
        )

        valid = np.isfinite(index)

        if condition == "greater":

            mask = index > threshold

        elif condition == "greater_equal":

            mask = index >= threshold

        elif condition == "less":

            mask = index < threshold

        elif condition == "less_equal":

            mask = index <= threshold

        elif condition == "between":

            if not isinstance(
                threshold,
                (tuple, list)
            ) or len(threshold) != 2:

                raise ValueError(
                    "For 'between', threshold must be "
                    "(lower, upper)."
                )

            lower, upper = threshold

            mask = (
                (index >= lower) &
                (index <= upper)
            )

        else:

            raise ValueError(
                "Unsupported condition. Use: "
                "greater, greater_equal, less, "
                "less_equal or between."
            )

        # Never classify NaN pixels.
        return mask & valid

    # =========================================================
    # REGION BOUNDS
    # =========================================================

    def mask_bounds(
        self,
        mask: np.ndarray
    ) -> Optional[Dict[str, float]]:
        """
        Return geographic bounds of all pixels in a mask.

        Output:
            left
            bottom
            right
            top
        """

        mask = np.asarray(mask, dtype=bool)

        rows, cols = np.where(mask)

        if rows.size == 0:
            return None

        min_row = int(rows.min())
        max_row = int(rows.max())

        min_col = int(cols.min())
        max_col = int(cols.max())

        # Convert pixel coordinates to map coordinates.
        top_left = rasterio.transform.xy(
            self.transform,
            min_row,
            min_col,
            offset="ul"
        )

        bottom_right = rasterio.transform.xy(
            self.transform,
            max_row,
            max_col,
            offset="lr"
        )

        return {
            "left": float(top_left[0]),
            "top": float(top_left[1]),
            "right": float(bottom_right[0]),
            "bottom": float(bottom_right[1]),
        }

    # =========================================================
    # INDEX SUMMARY
    # =========================================================

    def summarize(
        self,
        index: np.ndarray,
        index_name: str,
        threshold: Optional[float] = None,
        condition: str = "greater"
    ) -> Dict:

        index = self._prepare_index(index)

        stats = self.statistics(index)

        result = {
            "index": index_name.upper(),
            "statistics": stats,
        }

        # No threshold -> return statistics only.
        if threshold is None:
            return result

        mask = self.threshold_mask(
            index,
            threshold,
            condition
        )

        result["threshold"] = threshold
        result["condition"] = condition

        result["selected_pixels"] = int(
            np.count_nonzero(mask)
        )

        result["coverage_percentage"] = round(
            self.coverage_percentage(
                mask,
                index
            ),
            3
        )

        area = self.area_km2(mask)

        if area is not None:
            result["area_km2"] = round(
                area,
                4
            )

        result["bounds"] = self.mask_bounds(mask)

        return result

    # =========================================================
    # TRI-NETRA EVIDENCE FORMAT
    # =========================================================

    def generate_evidence(
        self,
        index: np.ndarray,
        index_name: str,
        threshold: float,
        condition: str = "greater"
    ) -> Dict:

        summary = self.summarize(
            index=index,
            index_name=index_name,
            threshold=threshold,
            condition=condition
        )

        evidence = {
            "type": "geospatial_index",
            "index": summary["index"],
            "mean_value": summary["statistics"]["mean"],
            "coverage_percentage": summary[
                "coverage_percentage"
            ],
            "selected_pixels": summary[
                "selected_pixels"
            ],
            "bounds": summary["bounds"],
            "crs": str(self.crs) if self.crs else None,
        }

        if "area_km2" in summary:
            evidence["area_km2"] = summary[
                "area_km2"
            ]

        return evidence


# =============================================================
# CONVENIENCE FUNCTIONS
# =============================================================

def analyze_index(
    raster_path: str,
    index: np.ndarray,
    index_name: str,
    threshold: Optional[float] = None,
    condition: str = "greater"
) -> Dict:

    analyzer = GeospatialIndexAnalyzer(
        raster_path
    )

    return analyzer.summarize(
        index=index,
        index_name=index_name,
        threshold=threshold,
        condition=condition
    )


# =============================================================
# EXAMPLE
# =============================================================

if __name__ == "__main__":

    from preprocessing.optical_processing import (
        OpticalProcessor
    )

    file_path = "data/input/Sample.tif"

    try:

        # ----------------------------------------------
        # Existing preprocessing module
        # ----------------------------------------------

        optical = OpticalProcessor(
            file_path
        )

        # Example Sentinel-2 band mapping.
        #
        # IMPORTANT:
        # These numbers depend on how YOUR GeoTIFF
        # stores its bands.
        #
        # B8  = NIR
        # B4  = Red
        # B3  = Green
        # B11 = SWIR
        #
        # Here we assume those bands are stored with
        # their Sentinel-2 band numbers/order in mind.
        #
        # Verify the actual mapping for your dataset.

        ndvi = optical.calculate_ndvi(
            nir_band=8,
            red_band=4
        )

        # ----------------------------------------------
        # Geospatial analysis
        # ----------------------------------------------

        analyzer = GeospatialIndexAnalyzer(
            file_path
        )

        result = analyzer.generate_evidence(
            index=ndvi,
            index_name="NDVI",
            threshold=0.30,
            condition="greater"
        )

        print("\n========== TRI-NETRA NDVI EVIDENCE ==========")

        for key, value in result.items():
            print(f"{key}: {value}")

        print("==============================================\n")

    except Exception as e:

        print(
            f"Geospatial index analysis failed: {e}"
        )