"""
Confidence Estimation
=====================

Calculates confidence for SATQueryAI conclusions using
structured evidence generated by evidence_generator.py.

Confidence factors:

1. Evidence strength
2. Source agreement
3. Modality agreement
4. Geospatial validation
5. Source diversity

All confidence values are normalized between 0.0 and 1.0.

Example:
    0.8042 = High confidence
"""


from typing import Any, Dict, List, Optional
STRENGTH_SCORES = {
    "strong": 1.0,
    "moderate": 0.7,
    "weak": 0.4,
    "unknown": 0.0,
}
WEIGHTS = {
    "evidence_strength": 0.35,
    "source_agreement": 0.25,
    "modality_agreement": 0.20,
    "geospatial_validation": 0.10,
    "source_diversity": 0.10,
}
class ConfidenceEstimator:
    """
    Estimates confidence from structured evidence.
    """

    def __init__(
        self,
        weights: Optional[Dict[str, float]] = None
    ):

        self.weights = (
            weights
            if weights is not None
            else WEIGHTS.copy()
        )

        self._validate_weights()

    def _validate_weights(self):

        total = sum(
            self.weights.values()
        )

        if abs(total - 1.0) > 0.001:

            raise ValueError(
                "Confidence weights must sum to 1.0. "
                f"Current total: {total}"
            )

    @staticmethod
    def calculate_evidence_strength(
        evidence: List[Dict[str, Any]]
    ) -> float:
        """
        Calculate average evidence strength.

        Returns:
            float between 0.0 and 1.0
        """

        if not evidence:
            return 0.0

        scores = []

        for item in evidence:

            strength = str(
                item.get(
                    "strength",
                    "unknown"
                )
            ).lower()

            score = STRENGTH_SCORES.get(
                strength,
                0.0
            )

            scores.append(
                score
            )

        if not scores:
            return 0.0

        return (
            sum(scores)
            /
            len(scores)
        )

    @staticmethod
    def calculate_source_agreement(
        evidence: List[Dict[str, Any]]
    ) -> float:
        """
        Measures whether categories are supported by
        multiple independent sources.

        1 source:
            0.5

        2 sources:
            0.8

        3+ sources:
            1.0

        Returns:
            float between 0.0 and 1.0
        """

        if not evidence:
            return 0.0

        category_sources = {}

        for item in evidence:

            category = item.get(
                "category",
                "general"
            )

            source = item.get(
                "source",
                "unknown"
            )

            if category not in category_sources:

                category_sources[
                    category
                ] = set()

            category_sources[
                category
            ].add(
                source
            )

        if not category_sources:
            return 0.0

        scores = []

        for sources in (
            category_sources.values()
        ):

            count = len(
                sources
            )

            if count >= 3:

                score = 1.0

            elif count == 2:

                score = 0.8

            elif count == 1:

                score = 0.5

            else:

                score = 0.0

            scores.append(
                score
            )

        return (
            sum(scores)
            /
            len(scores)
        )

    @staticmethod
    def calculate_modality_agreement(
        evidence: List[Dict[str, Any]]
    ) -> float:
        """
        Measures agreement across different modalities.

        Optical + SAR:
            1.0

        Optical + temporal:
            0.85

        SAR + temporal:
            0.85

        Multiple modalities:
            0.75

        Single modality:
            0.5

        Returns:
            float between 0.0 and 1.0
        """

        if not evidence:
            return 0.0

        category_modalities = {}

        for item in evidence:

            category = item.get(
                "category",
                "general"
            )

            modality = item.get(
                "modality",
                "unknown"
            )

            if modality is None:
                modality = "unknown"

            if category not in category_modalities:

                category_modalities[
                    category
                ] = set()

            category_modalities[
                category
            ].add(
                modality
            )

        scores = []

        for modalities in (
            category_modalities.values()
        ):

            modalities = {
                str(m).lower()
                for m in modalities
            }

            has_optical = any(
                "optical" in m
                for m in modalities
            )

            has_sar = any(
                "sar" in m
                for m in modalities
            )

            has_temporal = any(
                "temporal" in m
                or "bta" in m
                for m in modalities
            )

            if has_optical and has_sar:

                score = 1.0

            elif has_optical and has_temporal:

                score = 0.85

            elif has_sar and has_temporal:

                score = 0.85

            elif len(modalities) >= 2:

                score = 0.75

            elif len(modalities) == 1:

                score = 0.5

            else:

                score = 0.0

            scores.append(
                score
            )

        if not scores:
            return 0.0

        return (
            sum(scores)
            /
            len(scores)
        )

    @staticmethod
    def calculate_geospatial_validation(
        evidence: List[Dict[str, Any]]
    ) -> float:
        """
        Evaluate whether geospatial alignment evidence exists.

        Returns:
            float between 0.0 and 1.0
        """

        if not evidence:
            return 0.0

        alignment_items = []

        for item in evidence:

            source = str(
                item.get(
                    "source",
                    ""
                )
            ).lower()

            category = str(
                item.get(
                    "category",
                    ""
                )
            ).lower()

            if (
                "geospatial" in source
                or
                "alignment" in category
            ):

                alignment_items.append(
                    item
                )

        if not alignment_items:
            return 0.0

        scores = []

        for item in alignment_items:

            strength = str(
                item.get(
                    "strength",
                    "unknown"
                )
            ).lower()

            scores.append(
                STRENGTH_SCORES.get(
                    strength,
                    0.0
                )
            )

        return max(
            scores
        )
    @staticmethod
    def calculate_source_diversity(
        evidence: List[Dict[str, Any]]
    ) -> float:
        """
        Calculate confidence contribution from independent
        evidence sources.

        1 source:
            0.45

        2 sources:
            0.70

        3 sources:
            0.85

        4+ sources:
            1.0

        Returns:
            float between 0.0 and 1.0
        """

        if not evidence:
            return 0.0

        sources = set()

        for item in evidence:

            source = item.get(
                "source"
            )

            if source:

                sources.add(
                    source
                )

        count = len(
            sources
        )

        if count >= 4:
            return 1.0

        if count == 3:
            return 0.85

        if count == 2:
            return 0.70

        if count == 1:
            return 0.45

        return 0.0

    @staticmethod
    def confidence_level(
        score: float
    ) -> str:
        """
        Convert normalized confidence into a level.

        score is expected to be between 0.0 and 1.0.
        """

        if score >= 0.85:

            return "Very High"

        if score >= 0.70:

            return "High"

        if score >= 0.50:

            return "Moderate"

        if score >= 0.30:

            return "Low"

        return "Very Low"

    def calculate(
        self,
        evidence_package: Dict[str, Any]
    ) -> Dict[str, Any]:
        """
        Calculate the overall normalized confidence score.

        Returns:
            confidence_score between 0.0 and 1.0
        """

        if not isinstance(
            evidence_package,
            dict
        ):

            raise TypeError(
                "Evidence package must be a dictionary."
            )

        evidence = evidence_package.get(
            "evidence",
            []
        )

        if not isinstance(
            evidence,
            list
        ):

            raise TypeError(
                "'evidence' must be a list."
            )

        evidence_strength = (
            self.calculate_evidence_strength(
                evidence
            )
        )

        source_agreement = (
            self.calculate_source_agreement(
                evidence
            )
        )

        modality_agreement = (
            self.calculate_modality_agreement(
                evidence
            )
        )

        geospatial_validation = (
            self.calculate_geospatial_validation(
                evidence
            )
        )

        source_diversity = (
            self.calculate_source_diversity(
                evidence
            )
        )
        weighted_score = (

            evidence_strength
            *
            self.weights[
                "evidence_strength"
            ]

            +

            source_agreement
            *
            self.weights[
                "source_agreement"
            ]

            +

            modality_agreement
            *
            self.weights[
                "modality_agreement"
            ]

            +

            geospatial_validation
            *
            self.weights[
                "geospatial_validation"
            ]

            +

            source_diversity
            *
            self.weights[
                "source_diversity"
            ]
        )
        weighted_score = max(
            0.0,
            min(
                1.0,
                weighted_score
            )
        )

        confidence_score = round(
            weighted_score,
            4
        )

        level = (
            self.confidence_level(
                weighted_score
            )
        )

        return {

            "confidence_score":
                confidence_score,

            "confidence_level":
                level,

            "components": {

                "evidence_strength":
                    round(
                        evidence_strength,
                        4
                    ),

                "source_agreement":
                    round(
                        source_agreement,
                        4
                    ),

                "modality_agreement":
                    round(
                        modality_agreement,
                        4
                    ),

                "geospatial_validation":
                    round(
                        geospatial_validation,
                        4
                    ),

                "source_diversity":
                    round(
                        source_diversity,
                        4
                    ),
            },

            "weights":
                self.weights.copy(),

            "evidence_count":
                len(evidence),

            "interpretation":
                self.generate_interpretation(
                    confidence_score,
                    level
                ),
        }

    @staticmethod
    def generate_interpretation(
        score: float,
        level: str
    ) -> str:
        """
        Generate a human-readable interpretation.
        """

        if score >= 0.85:

            return (
                "The conclusion is strongly supported "
                "by multiple independent evidence sources "
                "and/or modalities."
            )

        if score >= 0.70:

            return (
                "The conclusion has strong supporting "
                "evidence, although some uncertainty "
                "may remain."
            )

        if score >= 0.50:

            return (
                "The conclusion has moderate supporting "
                "evidence and should be interpreted with "
                "some caution."
            )

        if score >= 0.30:

            return (
                "The available evidence is limited. "
                "The conclusion should be treated cautiously."
            )

        return (
            "The available evidence is insufficient "
            "to support a reliable conclusion."
        )
    def estimate(
        self,
        evidence_package: Dict[str, Any]
    ) -> Dict[str, Any]:

        return self.calculate(
            evidence_package
        )

confidence_engine = (
    ConfidenceEstimator()
)


def calculate_confidence(
    evidence_package: Dict[str, Any]
) -> Dict[str, Any]:

    return confidence_engine.calculate(
        evidence_package
    )


if __name__ == "__main__":

    print(
        "\n========== CONFIDENCE TEST =========="
    )


    example_evidence = {

        "evidence": [

            {
                "id": 1,

                "source": "SIA",

                "observation": (
                    "The image contains vegetation "
                    "and buildings."
                ),

                "strength": "moderate",

                "modality": "optical",

                "category": "vegetation",
            },

            {
                "id": 2,

                "source": "BTA",

                "observation": (
                    "Vegetation has decreased."
                ),

                "strength": "moderate",

                "modality": "temporal",

                "category": "vegetation",
            },

            {
                "id": 3,

                "source": "Cross-Modal",

                "observation": (
                    "Optical and SAR indicate "
                    "built-up structures."
                ),

                "strength": "strong",

                "modality": "optical+sar",

                "category": "building",
            },

            {
                "id": 4,

                "source": "Geospatial Alignment",

                "observation": (
                    "Source and reference rasters "
                    "are spatially aligned."
                ),

                "strength": "strong",

                "modality": "geospatial",

                "category": "alignment",
            },
        ]
    }

    result = calculate_confidence(
        example_evidence
    )

    print(
        f"\nConfidence Score: "
        f"{result['confidence_score']}"
    )

    print(
        f"Confidence Level: "
        f"{result['confidence_level']}"
    )

    print(
        "\nComponents:"
    )

    for key, value in (
        result[
            "components"
        ].items()
    ):

        print(
            f"{key}: {value}"
        )

    print(
        "\nInterpretation:"
    )

    print(
        result[
            "interpretation"
        ]
    )

    print(
        "\n===================================="
    )